### PR TITLE
Inverted tags

### PR DESCRIPTION
**Pull request by royshil**
This patch allows reading "inverted" tags (white instead of black), by flipping the detected "bits"

### CODE REVIEW

**Comment by qbonnard** [comment]
Nice, thanks ! You even made the effort of using our weir naming conventions ;)
Let me just fine some time in the coming days to compile and play with it a bit, and I'll merge. Or is there an emergency on your side ?

**Comment by royshil** [comment]
@qbonnard super low priority :smile: 
I'll clean up some stuff I've forgotten soon

**Comment by qbonnard** [comment]
Done ! Thanks again @royshil !
Now I have a lot of curiosity ;) What do you do with chilitags ? What's your usecase for inverted tags ? Did you managed to run the tests (I gave up with the 3.x releases of opencv) ? Ok, that's enough questions ;)

**Comment by royshil** [comment]
@qbonnard i'm using it in a research project with projected AR. The inverted tags I needed because of a misprint of a tag, where it is inverted... can't print again (high cost). I haven't run the tests... should I do it?

**Comment by qbonnard** [comment]
@royshil No worries for the tests, I added one for inverted tags for good measures, and Travis runs them anyway ;)
I hope I'll remember to check your publications to know more about your project ! Have fun.

**Pull request merged**
