### PR TITLE
Kalman filter prototype

### PR DESCRIPTION
**Pull request by ayberkozgur**
This PR is an early preview of Kalman filtering to 6D tag pose. Comes with hardcore c++11 `std::map::emplace()` and related syntax :)

Is a partial solution to #19.

For now, the quick & dirty covariance calibration seems to work decent enough. Please test further.

~~A huge issue now is gimbal lock and discontinuities in angle. We need quaternions to fix this.~~ done

In the near future, more goodies such as 

- ~~Calibration API~~ done
- ~~Enable/disable on demand API~~ done
- ~~Quaternions~~ done
- ~~IMU integration~~ done, see also https://github.com/chili-epfl/qml-imu
- ~~Optimizations~~ pretty much done
- ~~Sample~~ done
- ~~Remove `Filter` completely~~ done
- ~~Add tag discard mechanism~~ done
- ~~Fully document all math involved~~ done

will follow.

### CODE REVIEW

**Comment by ayberkozgur** [comment]
Everything seems to be OK.

**Comment by johnnyx811** [comment]
guys I missed some messages, but quaternions have singularities...you
should use exponential maps

2015-01-05 9:24 GMT+01:00 Ayberk Özgür <notifications@github.com>:

**Comment by ayberkozgur** [comment]
As far as I know, there are no singularities in quaternions, that's one of the main reasons why we prefer them over Euler or angle-axis representations.

**Comment by johnnyx811** [comment]
sry, you are right. Now I remember: there is still one argument for
replacing quaternions with exponential maps in linear Kalman filtering. 3D
rotations have 3 degrees of freedoms, quaternions have 4 dimensions,
exponential maps have 3. If I remember correctly in quaternions you have a
problem of scale which may suggest some sort of normalizations. This
problem is solved in exponential maps.

I don't remember exactly all the pros and cons for this rotation
representation: but here they should discuss them.
http://www.cs.cmu.edu/~spiff/moedit99/expmap.pdf

All the best

Andrea

2015-01-05 9:37 GMT+01:00 Ayberk Özgür <notifications@github.com>:

**Comment by ayberkozgur** [comment]
As far as I know, the exponential map concept is exactly what we know as the 3x3 rotation matrix. Due to redundancies, it still has 3 DOF despite storing 9 values. Quaternions store 4 values but they are unit quaternions so one DOF is reduced and they still have 3 DOF. The pro of using 3x3 rotation matrices is that we can do matrix multiplications and combine rotations/rotate vectors very cheaply. This doesn't translate well into things like Kalman filters where we don't have to combine rotations or rotate vectors but we have to process rotations as a state vector. That's why we (at least I) don't use 9 values in the state vector because it's overkill.

**Comment by ayberkozgur** [comment]
Having read the exponential part of the paper you provided, I would say the concept described there is interesting. It is only very slightly different than what we use (unit quaternions). Still, we (at least I) do a sinc-like epsilon check that is the core idea of the slight modification described in the paper; you can see it in https://github.com/ayberkozgur/chilitags/blob/kalman/src/Filter3D.cpp#L280 and https://github.com/ayberkozgur/chilitags/blob/kalman/src/Filter3D.cpp#L297.

**Comment by johnnyx811** [comment]
yep that's correct and you divide by quaternion norm. now you have three
independent components (required from the classic Kalman Filter) instead of
four.

2015-01-05 11:12 GMT+01:00 Ayberk Özgür <notifications@github.com>:

**Comment by qbonnard** [comment]
@johnnyx811 I think you mixed up your dates. 1st of January is time for new Years' resolution, not April Fools' jokes... Or did you have a bad break up with Rodrigues ? ;)

**Comment by qbonnard** [comment]
@ayberkozgur I was thinking that it would be nice to have some test or evaluation of Kalman before merging this, but this may take a big while... How annoying is it to wait more ?

**Comment by ayberkozgur** [comment]
Well, most probably I won't be developing Chilitags until somewhere around the end of March because I have to publish; I'll probably get fired otherwise :)

**Comment by severin-lemaignan** [comment]
@ayberkozgur I confirm :-)

**Comment by qbonnard** [comment]
Well if you get fired coding Chilitags, you'll have more time for more coding. That's a double win for Chilitags ;) Just use a fake GitHub account, I'm sure no one will notice... Join me to the dark side of no publications. We have cookies.

So it's not a problem if I stall this until end of March then ?

**Comment by ayberkozgur** [comment]
It's easy for you to say, you already have your PhD :)

I don't see the point of delaying this for three months for added tests. I can understand your desire to have tests for all features but the current PR is quite big as it is. It would better be suited as an issue for now.

**Comment by qbonnard** [comment]
Finally merged this PR, since I probably won't add to it before March. R.I.P. hopes of tests ;)

Many thanks again !

**Pull request merged**
