### PR TITLE
Uncrustify source files

### PR DESCRIPTION
**Pull request by SyrianSpock**
This PR simply applies the uncrustify config to the source files.
The use of uncrustify and integration in pre-commit hook is also documented.

### CODE REVIEW

**Comment by hrilabplymouth** [comment]
I might have missed it, but have you included `uncrustify.cfg` in your PR?

**Comment by SyrianSpock** [comment]
@hrilabplymouth No, it was already there. I just ran it on the existing source code and documented usage for future developers.

**Comment by qbonnard** [comment]
Thanks, that was long overdue, and the README/precommit hook is a really nice touch :)
I'll have a look at whether uncrustify wasn't too zealous before merging, I suppose there is no emergency on your side ?

**Comment by SyrianSpock** [comment]
@qbonnard No emergency.

**Comment by qbonnard** [comment]
Well I did take my time to just rebase and push ;)
Many thanks again :)

**Pull request merged**
